### ISSUE TITLE
Bug: Pypi django-trench Package Does Not Contain Migration 0004.

### ISSUE THREAD

**Issue by evanottinger** [merixstudio/django-trench#199]
**Describe the bug**
The pypi django-trench package v0.3.1 is out of sync with the current state of the main branch of the codebase. Because of this, a [migration that was added to the codebase a month](https://github.com/merixstudio/django-trench/blob/develop/trench/migrations/0004_alter_mfamethod_id_mfamethod_unique_user_is_primary_and_more.py) ago does not exist in the package. This requires the user to manually run `python manage.py makemigrations` to first create the migration and then apply it to their database.

Since trench is a 3rd party library, when the user makes the migrations, it is not added to their existing codebase. This is problematic when the user extends a model in the trench library and their app's migrations contain a dependency to the generated trench migration, which does not exist in the package.

**To Reproduce**
1. Create Django project and implement trench library as per documented instructions.
2. Create a custom application, for example "custom_auth".
3. Extend a model from the trench library.
4. Make migrations and commit them to the code base.

**Expected behavior**
The pypi package should contain all migrations required to migrate the current version.

**Stack Trace**
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 114, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/migrations/loader.py", line 276, in build_graph
    self.graph.validate_consistency()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/migrations/graph.py", line 198, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/migrations/graph.py", line 198, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/migrations/graph.py", line 60, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration custom_auth.0001_initial dependencies reference nonexistent parent node ('trench', '0004_alter_mfamethod_id')
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: N/A
 - Version: 0.3.1

**Additional context**
N/A

**Comment by pandafy** [comment]
Hello @evanottinger! i was trying out this package when I stumble across your issue. I have installed django-trench from PyPI as suggested in the documentation. You can verify the django-trench version from below:

```
# pip show django-trench
Name: django-trench
Version: 0.3.1
Summary: REST Multi-factor authentication package for Django
Home-page: https://github.com/merixstudio/django-trench
Author: Merixstudio
Author-email: trench@merixstudio.com
License: MIT License
Location: /opt/openwisp2/env/lib/python3.10/site-packages
Requires: pyotp, smsapi-client, twilio, yubico-client
Required-by: 
```

Yes, there are only three migrations available through the package 

```
# ./manage.py showmigrations trench 
System check identified some issues:

 [X] 0001_initial
 [X] 0002_auto_20190111_1403
 [X] 0003_auto_20190213_2330
 ````

In my development environment, I don't see makemigrations creating a new migration 


```
# ./manage.py makemigrations --dry-run 
System check identified some issues:

No changes detected
```

I think you have installed stable version from PyPI, but you are basing your work on the development version of the package.

**Comment by evanottinger** [comment]
I'm sorry for not following up sooner. I believe this is correct. In my project settings, I overwrote `DEFAULT_AUTO_FIELD` with `BigAutoField`. When I ran `makemigrations`, this caused Django to create (my missing) migration to update the auto field of the trench library.  User error :)
