### ISSUE TITLE
Authentication credentials were not provided

### ISSUE THREAD

**Issue by lanthos** [merixstudio/django-trench#34]
Hello again!

Also running into a separate issue where I'm able to get the ephemeral_token (I changed the code in my virtualenv to return a 16 digit key and I was able to add it to Google auth) but when I send that plus the generated code I get the following:

`curl -X POST http://localhost:8000/auth/login/code/ -d 'code=260286&ephemeral_token=6c59369d-2f77-4e90-939d-be9ab5794af8-pmh8ix-791be5511d3a6d96f594a5d3dfd3629075f1b366'`

`{"status_code":401,"message":"Authentication credentials were not provided."}`

Upon looking a bit further it looked like part of the problem is that we are using UUIDs for the PKs on our User objects so it was causing problems with `user_pk, ts_b36, hash = token.split('-')` but making local changes to that and the `_make_token_with_timestamp` method to test things, still provides that error even when it's using a different character to separate out those items and split on it instead (I used : to test).

I'm using Python 3.6.5
Django==1.11.11
djangorestframework==3.8.2
djangorestframework-simplejwt==2.1 

Any help here would be appreciated as well.  Let me know if there is any other information I can provide. Thank you!

**Comment by tallpol3** [comment]
Thanks Jeremy. Need to have a look at this certainly. Can you share the way how UUIDs for PKs are implemented in your project?

**Comment by lanthos** [comment]
Hi Bartek,

Certainly!  `id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)`

This will generate a PK similar to: `6561cc29-5c68-487e-bcb4-0563d7ec3a1b`

As the app is splitting on the `-` character that causes some problems with the expected results (although I don't think that's the reason I'm getting the 401, since when I changed that locally I still got the 401).

**Comment by jmaslanka** [comment]
My bad, standard Django's implementation uses split by `-` (https://github.com/django/django/blob/c52ecbda615594750ae59b789313a29893950b3d/django/contrib/auth/tokens.py#L31) and I just followed that without realizing UUID also can be used as PK (CharFields can too...). This needs to be changed in some way if we want to keep PK in token.

**Comment by jmaslanka** [comment]
Not a bad idea, would like to keep DB queries to minimum though (only one `.get()` to User table now.)

**Comment by jmaslanka** [comment]
But... Is MFAMethod object created at this point?

**Comment by tallpol3** [comment]
@jmaslanka MFAMethod is already there cause we're using 2nd step of authentication, means user activated at least one method already.

I came to another idea. I know what's the purpose of using token, but in this case we could return user's pk separately to ephemeral_token in serializer, what would save as splitting it from a token and make it independent from whatever value is used in user's pk.

**Comment by jmaslanka** [comment]
@tallpol3 But what if its the first method? Well, since user should be logged in at this point we can just take logged user and remove pk from this token ¯\_(ツ)_/¯

**Comment by tallpol3** [comment]
Hi Jemery. 
Turns out that solution is actually quite simple. Checkout #36. I've run all tests on User model using UUID as PK and it seems to work fine.

**Comment by lanthos** [comment]
@tallpol3 Very nice!

**Comment by lanthos** [comment]
@tallpol3 I've made the change to my local copy but I'm still running into issues. :( I'm able to activate everything correctly but when I try and connect to /auth/login/code/ I'm getting a 401 saying the credentials were not provided.  Is there anything that you can think of that would be causing this bit not to work or how I can further troubleshoot this?   I use PAW for accessing API endpoints but here's the cURL it generates based upon the settings I'm using.  Let me know if there is any other information that I can provide.  Cheers!

`curl -X "POST" "http://localhost:8000/auth/login/code/" \
     -H 'Content-Type: text/plain; charset=utf-8' \
     -H 'Cookie: csrftoken=HNCrpod5RpAeyCRiC0Pu6EByGIxT3AljpH0avjFGgDpCbnaSW0f78mSIDax4BAS9' \
     -d "code=146169&ephemeral_token=6561cc29-5c68-487e-bcb4-0563d7ec3a1b-pmtszm-a078ab055b2b23123f7895f1d9918a3ca6e40530"`

**Comment by tallpol3** [comment]
@lanthos What's the _WWW-Authenticate_ header on the response? 401 you're getting is a generic DRF exemption and the endpoint view inherit from GenericAPIView, so I'd start checking from DEFAULT_AUTHENTICATION_CLASSES.

**Comment by lanthos** [comment]
@tallpol3 here are the headers:

HTTP/1.0 401 Unauthorized
Content-Type: application/json
WWW-Authenticate: Bearer realm="api"
Vary: Accept, Accept-Language, Cookie, Origin
Allow: POST, OPTIONS
Content-Language: en
X-Frame-Options: SAMEORIGIN
Content-Length: 77
Server: Werkzeug/0.14.1 Python/3.6.5
Date: Tue, 12 Feb 2019 20:57:53 GMT

{"status_code":401,"message":"Authentication credentials were not provided."}

We are using a middleware that will force things to require a login if we don't provide put the endpoint in an exception list as per http://stackoverflow.com/questions/2164069/best-way-to-make-djangos-login-required-the-default.  I was not able to get /auth/login/ to work until I put it in the exception and it works fine now.  Adding /auth/login/code/ appears to not be working as per that header though.  We have the following for the authentication classes.  I did have to comment out SessionAuthentication when I install trench, as I was getting CSRF errors on the /auth/login/ endpoint when it's enabled.

`    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        # "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),`

**Comment by tallpol3** [comment]
@lanthos According to the header, Simple JWT authentication, being the first default, kicks in on the view where it shouldn't, so please dive deeper into your middleware.
 If you're using login_required, consider replacing permission policy with [DRF approach](https://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy)

**Comment by lanthos** [comment]
I've removed all of the middleware we were using and I was still getting the same 401.  We had the default_permission_classes setup as well with `rest_framework.permissions.IsAuthenticated`.  So I've uncommented that and I'm getting slightly further.  Any ideas why this part would be failing?  It seems to not like the backup_code.

`Traceback (most recent call last):
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/trench/views/base.py", line 80, in post
    serializer.is_valid(raise_exception=True)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/trench/serializers.py", line 293, in validate
    auth_method.backup_codes,
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/trench/utils.py", line 252, in validate_backup_code
    validated_codes = [_ for _ in backup_codes if check_password(value, _)]
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/trench/utils.py", line 252, in <listcomp>
    validated_codes = [_ for _ in backup_codes if check_password(value, _)]
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/contrib/auth/hashers.py", line 51, in check_password
    must_update = hasher_changed or preferred.must_update(encoded)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/contrib/auth/hashers.py", line 358, in must_update
    salt, data) = self._decode(encoded)
  File "/Users/lanthos/.virtualenvs/pearl/lib/python3.6/site-packages/django/contrib/auth/hashers.py", line 386, in _decode
    assert len(bits) == 6
AssertionError`

**Comment by lanthos** [comment]
Update: if I set `"ENCRYPT_BACKUP_CODES": False` then I'm able to successfully authenticate using an ephemeral_token and the access code that is generated from my app.  I still need to look into why having `"DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",)` set causes this to not correctly pass along the credentials to the /auth/login/code/ endpoint but this is some progress!

**Comment by lanthos** [comment]
ok got it!  I'm not sure how to make this fix work for the overall project but what I ended up having to do was add `permission_classes = [AllowAny, ]` to the `MFACodeLoginMixin` class.  This will make sure that there was nothing like a default permission class that was getting in the way of hitting that endpoint.  Since we have the default permission class to be IsAuthenticated we could never get to this endpoint as it was.

**Comment by tallpol3** [comment]
Seems that we have the issue solved. Please check new release.
