### ISSUE TITLE
Annoying error with drf_yasg

### ISSUE THREAD

**Issue by reyesvicente** [merixstudio/django-trench#95]
After I installed `django-trench` I started getting this error. I tried to look it up online but didn't see any fix to it.

```
django          | Traceback (most recent call last):
django          |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
django          |     return view_method()
django          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 109, in get_serializer
django          |     kwargs.setdefault('context', self.get_serializer_context())
django          |   File "/usr/local/lib/python3.8/site-packages/trench/views/base.py", line 204, in get_serializer_context
django          |     raise NotFound()
django          | rest_framework.exceptions.NotFound: Not found.
django          | WARNING 2021-04-02 02:07:55,088 base 29 139791338682112 view's RequestMFAMethodDeactivationView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
django          | Traceback (most recent call last):
django          |   File "/usr/local/lib/python3.8/site-packages/trench/views/base.py", line 199, in get_serializer_context
django          |     'name': self.kwargs['method'],
django          | KeyError: 'method'
django          | 
django          | During handling of the above exception, another exception occurred:
django          | 
django          | Traceback (most recent call last):
django          |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
django          |     return view_method()
django          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 109, in get_serializer
django          |     kwargs.setdefault('context', self.get_serializer_context())
django          |   File "/usr/local/lib/python3.8/site-packages/trench/views/base.py", line 204, in get_serializer_context
django          |     raise NotFound()
django          | rest_framework.exceptions.NotFound: Not found.
```

**Comment by bplociennik** [comment]
This view is not existing anymore in the recent version of the trench.
@reyesvicente let me know if you cannot swap to a new version of the trench, I will be happy to help you with the older version issues then (feel free to reopen this issue in that case).
